; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200 
build_flags = -Wno-narrowing

 ; ---------- 让 TFT_eSPI 忽略库目录里的 User_Setup.h ----------
  -DUSER_SETUP_LOADED=1

  ; ---------- 屏幕驱动与尺寸 ----------
  -DST7735_DRIVER=1
  -DTFT_WIDTH=128
  -DTFT_HEIGHT=160
  -DST7735_REDTAB=1
  -DST7735_OFFSET_X=0
  -DST7735_OFFSET_Y=1

  ; ---------- 颜色顺序（解决颜色反转）----------
  -DTFT_RGB_ORDER=TFT_RGB

  ; ---------- 引脚接线 ----------
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=26
  -DTFT_DC=25
  -DTFT_RST=2

  ; ---------- 字体支持（平滑字体必须开）----------
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1

  ; ---------- SPI 速率 ----------
  -DSPI_FREQUENCY=27000000
   -DSPI_READ_FREQUENCY=20000000
  -DSPI_TOUCH_FREQUENCY=2500000
  ; -DSPI_FREQUENCY=10000000


lib_deps =
  bodmer/TFT_eSPI
  arduino-libraries/NTPClient
  knolleary/PubSubClient
  mathertel/OneButton